# -*- coding: utf-8 -*-
"""MLCOurse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPxK_8lLaW9u09ynL2pp7sIFZlssWsI0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import tensorflow as tf
#print("TensorFlow version:", tf.__version__)

#from google.colab import files
#uploaded = files.upload()

house_data = pd.read_csv("Housing.csv")
#print(house_data)
size = house_data['area']
price = house_data['price']

#ML handle arrays not data-frames
x = np.array(size).reshape(-1,1)
y = np.array(price).reshape(-1,1)
#print(y)

#we use linear regression + fit in the training
model = LinearRegression()
model.fit(x,y)
#
regression_model_mse = mean_squared_error(x,y)
print("MSE:" , np.sqrt(regression_model_mse))
print("R square value:",model.score(x,y))
#we can get the b values after the model fit

#this is the b1 value
print(model.coef_[0])
#this is the b0 in our model
print(model.intercept_[0])


plt.scatter(x,y,color='green')
plt.plot(x, model.predict(x), color='black')
plt.title("linear regression")
plt.xlabel("size")
plt.ylabel("prize")
plt.show()

print("prediction of the price",model.predict([[20]]))

print("prediction of the price",model.predict([[200000]]))

from google.colab import files
uploaded = files.upload()