# -*- coding: utf-8 -*-
"""logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4LLOh1lpHrptIkUPTpn6nfaZWY1BRjL
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


credit_data =pd.read_csv("credit_data.csv")

# Check for missing values (optional, for inspection)
# print("Missing values before imputation:")
# print(credit_data.isnull().sum())

# Impute missing values with the mean of the respective column
# This assumes 'income', 'age', 'loan' are the columns with potential NaNs
for col in ["income", "age", "loan"]:
    if credit_data[col].isnull().any():
        credit_data[col] = credit_data[col].fillna(credit_data[col].mean())

# print("\nMissing values after imputation:")
# print(credit_data.isnull().sum())

features = credit_data[["income", "age", "loan"]]
target = credit_data.default

features_train, features_test, target_train, target_test = train_test_split(features, target, test_size = 0.3)

model = LogisticRegression()
model.fit(features_train, target_train)

predictions = model.predict(features_test)
#tells the performance report of the model
print(confusion_matrix(target_test,predictions))
print(accuracy_score(target_test,predictions))

new_customer =pd.DataFrame({
    'income':[10000],
    'age' :[50],
    'loan':[880]
})

predicted_default = model.predict(new_customer)
print("Predicted Default (0=No, 1=Yes):", predicted_default)